#!/bin/bash

# Scripts for checking parameters and submitting tasks



# Function to print help message
print_help() {
    echo "Usage: $0 [options]"
    echo ""
    echo "Options:"
    echo "  -i, --input_dir <path>       Specify the input file path"
    echo "  -o, --output_dir <path>      Specify the output file path"
    echo "  -c, --config <file>      Specify the configuration file"
    echo "  -h, --help               Display this help message"
}

# Initialize variables
input_dir=""
output_dir=""
config=""

# Parse command-line arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            print_help
            exit 0
            ;;
        -i|--input_dir)
            input_dir="$2"
            shift 2
            ;;
        -o|--output_dir)
            output_dir="$2"
            shift 2
            ;;
        -c|--config)
            config="$2"
            shift 2
            ;;
        *)
            echo "Invalid argument: $1"
            print_help
            exit 1
            ;;
    esac
done

# Check if required arguments are provided
if [[ -z "$input_dir" ]] || [[ -z "$output_dir" ]] || [[ -z "$config" ]]; then
    echo "Error: You must specify --input_dir, --output_dir, and --config options."
    print_help
    exit 1
fi

# Check if output path is a directory or a file
if [[ ! -d "$input_dir" ]]; then
    echo "Error: Input path does not exist: $input_dir"
    exit 1
fi

# Change directory to the project path
SCRIPT_DIR=$(dirname "$(realpath "$0")")
cd $SCRIPT_DIR

source ./scripts/utils.sh

# Multisample parallel pipeline
samples="$(ls ${input_dir})"
for sample in ${samples};do
    log_info "Run pipeline for ${sample}..."
    (
        ./scripts/pipeline.sh "$input_dir" "$output_dir" "$sample" "$config"
        log_info "Pipeline for ${sample} completed!"
    ) &
done
# Wait all samples to complete
wait

# Aggregate results
log_info "Aggregating results of this batch..."
./scripts/summary.py \
    -s "${samples}" \
    -o "${output_dir}" \
    -c "${config}"

log_info "All samples have been processed."